apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker
  template:
    metadata:
      labels:
        app: docker
    spec:
      containers:
      - name: docker
        image: kunal9079/dockerimage:v1
        ports:
        - containerPort: 9090
